services:
  jupyter-lab:
    build: .
    container_name: jupyter-lab
    working_dir: /root/jupyter
    entrypoint: >
      poetry run jupyter lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
    volumes:
      - ./src:/root/jupyter
      - ./data:/root/data
    ports:
      - "8888:8888"
