services:
  jupyter-lab:
    build: .
    container_name: ${CONTAINER_NAME:-jupyter-lab}
    working_dir: /root/jupyter
    entrypoint: >
      poetry run jupyter lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=${NOTEBOOK_TOKEN:-}
    volumes:
      - ./src:/root/jupyter
      - ./data:/root/data
    ports:
      - "${HOST_PORT:-8888}:8888"
